import { nanoid } from 'nanoid';import { appendObject,clearSheet,deleteSheet,ensureHeader,readObjects,updateObjectByKey } from '@/lib/googleSheets';import { env } from '@/lib/env';import { exerciseSeed } from '@/data/exercises.seed';import { workoutTemplateSeed } from '@/data/workoutTemplates.seed';import type { UserIndexRow } from '@/types/fitness';
export const SYSTEM_HEADERS={System_Config:['key','value','updatedAt'],Users_Index:['userId','email','name','sheetPrefix','role','status','passwordHash','resetTokenHash','resetExpiresAt','createdAt','updatedAt','deletedAt','note'],Admin_Actions:['actionId','actionType','targetUserId','targetEmail','detail','adminName','createdAt'],Sync_Logs:['logId','userId','sheetName','actionType','status','errorMessage','retryCount','createdAt','updatedAt'],Delete_Requests:['requestId','userId','email','deleteType','status','requestedAt','completedAt','note'],Exercise_Library:['id','nameVi','nameEn','category','primaryMuscles','secondaryMuscles','level','suitableFor','equipment','hasJump','kneePressure','lowerBackPressure','shoulderPressure','wristPressure','safetyNotes','stepsVi','commonMistakes','formTips','easierVariation','harderVariation','imagePlaceholder','videoPlaceholder'],Workout_Templates:['templateId','sessionsPerWeek','name','split']};
export const USER_HEADERS={Profile:['userId','profileJson','metricsJson','updatedAt'],Measurements:['measurementId','userId','weightKg','heightCm','neckCm','chestCm','waistCm','hipCm','thighCm','armCm','calfCm','restingHeartRate','dailySteps','metricsJson','createdAt'],Assessments:['assessmentId','userId','assessmentJson','level','createdAt'],WorkoutPlans:['planId','userId','planJson','createdAt','updatedAt'],WorkoutLogs:['logId','sessionId','userId','dayIndex','status','exerciseId','exerciseName','plannedSet','completedSet','plannedRepOrTime','actualRepOrTime','skipReason','startedAt','endedAt','durationSec','createdAt'],WorkoutSessionEvents:['eventId','sessionId','userId','dayIndex','eventType','exerciseId','exerciseName','plannedSet','completedSet','plannedRepOrTime','actualRepOrTime','skipReason','detail','createdAt'],NutritionLogs:['nutritionId','userId','calories','proteinG','fatG','carbG','note','createdAt'],Notifications:['notificationId','userId','type','message','status','createdAt','readAt'],PendingSync:['pendingId','userId','kind','payloadJson','status','retryCount','errorMessage','createdAt','updatedAt']};
export const userSheetName=(p:string,n:keyof typeof USER_HEADERS)=>`${p}_${n}`;
export async function initSystemSheets(){for(const [s,h] of Object.entries(SYSTEM_HEADERS))await ensureHeader(s,h);const ex=await readObjects('Exercise_Library',SYSTEM_HEADERS.Exercise_Library);if(ex.length<180){await clearSheet('Exercise_Library',SYSTEM_HEADERS.Exercise_Library);for(const e of exerciseSeed)await appendObject('Exercise_Library',SYSTEM_HEADERS.Exercise_Library,e)}const tpl=await readObjects('Workout_Templates',SYSTEM_HEADERS.Workout_Templates);if(!tpl.length)for(const t of workoutTemplateSeed)await appendObject('Workout_Templates',SYSTEM_HEADERS.Workout_Templates,t)}
export async function getUsers(){await initSystemSheets();return readObjects<UserIndexRow>('Users_Index',SYSTEM_HEADERS.Users_Index)}
export async function getUserByEmail(email:string){return (await getUsers()).find(u=>u.email.toLowerCase()===email.toLowerCase())}
export async function getUserById(userId:string){return (await getUsers()).find(u=>u.userId===userId)}
async function nextPrefix(){const used=new Set((await getUsers()).map(u=>u.sheetPrefix));for(let i=1;i<=env.MAX_ACTIVE_USERS+100;i++){const p=`U_${String(i).padStart(3,'0')}`;if(!used.has(p))return p}throw new Error('Không còn mã sheetPrefix khả dụng.')}
export async function createUserSheets(prefix:string){for(const [n,h] of Object.entries(USER_HEADERS))await ensureHeader(`${prefix}_${n}`,h)}
export async function registerUser(a:{email:string;name:string;passwordHash:string}){await initSystemSheets();const old=await getUserByEmail(a.email);if(old&&old.status!=='deleted')throw new Error('Email này đã tồn tại trong hệ thống.');const active=(await getUsers()).filter(u=>u.status==='active'||u.status==='locked');if(active.length>=env.MAX_ACTIVE_USERS)throw new Error(`Hệ thống chỉ hỗ trợ tối đa ${env.MAX_ACTIVE_USERS} tài khoản active.`);const now=new Date().toISOString();const user:UserIndexRow={userId:`usr_${nanoid(12)}`,email:a.email.toLowerCase(),name:a.name,sheetPrefix:await nextPrefix(),role:'user',status:'active',passwordHash:a.passwordHash,resetTokenHash:'',resetExpiresAt:'',createdAt:now,updatedAt:now,deletedAt:'',note:''};await appendObject('Users_Index',SYSTEM_HEADERS.Users_Index,user);await createUserSheets(user.sheetPrefix);return user}
export async function updateUser(userId:string,patch:Partial<UserIndexRow>){const u=await getUserById(userId);if(!u)throw new Error('Không tìm thấy tài khoản.');await updateObjectByKey('Users_Index',SYSTEM_HEADERS.Users_Index,'userId',userId,{...u,...patch,updatedAt:new Date().toISOString()})}
export async function hardDeleteUserSheets(userId:string){const u=await getUserById(userId);if(!u)throw new Error('Không tìm thấy tài khoản.');for(const n of Object.keys(USER_HEADERS))await deleteSheet(`${u.sheetPrefix}_${n}`);await updateUser(userId,{status:'deleted',deletedAt:new Date().toISOString(),note:'Đã hard delete nhóm sheet riêng.'});return u}
